### PR TITLE
Update pom.xml(Resource pack conversion)

### PR DESCRIPTION
**Pull request by zimzaza4**
Resource pack conversion

### CODE REVIEW

**Comment by Hellohi3654** [comment]
yo thank you

**Comment by zimzaza4** [comment]
hey i made a CustomModelData mappings
https://github.com/zimzaza4/Geyser/tree/CustomModelDataMappings
```
custom-model-data-mappings:
  - "123456;mytool;true"
  - "200001;mydiamond;false"
```

**Comment by zimzaza4** [comment]
https://media.discordapp.net/attachments/613163671870242842/901462275284664340/Screenshot_20211023_205220_com.mojang.minecraftpe.jpg

**Comment by Hellohi3654** [comment]
> hey i made a CustomModelData mappings https://github.com/zimzaza4/Geyser/tree/CustomModelDataMappings
> 
> ```
> custom-model-data-mappings:
>   - "123456;mytool;true"
>   - "200001;mydiamond;false"
> ```

Cool thank you

**Pull request merged**
